services:
  dpsrv-mongo:
    container_name: dpsrv-mongo-${tag:-latest}
    image: dpsrv/mongo:${tag:-latest}
    build: .
    hostname: $HOSTNAME.dpsrv.me
    env_file:
      - ${DPSRV_HOME}/rc/secrets/mongo/mongo.env
      - ${DPSRV_HOME}/rc/secrets/local/${HOSTNAME}/local.env
    ports:
      - '27017/tcp'
    volumes:
      - ${DPSRV_HOME}/rc/secrets/mongo/conf/:/etc/mongo/
      - ${DPSRV_HOME}/srv/mongo:/data/db/
      - ${DPSRV_HOME}/rc/secrets/letsencrypt/:/etc/letsencrypt/:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
networks:
  default:
    name: dpsrv
    external: true
volumes:
  db:
