services:
  mongo:
    container_name: mongo
    image: mongo:latest
    env_file: ${DPSRV_HOME}/rc/secrets/mongo/mongo.env
    ports:
      - '27017:27017'
    volumes:
      - ${DPSRV_HOME}/rc/secrets/mongo/conf/:/etc/mongo/
      - db:/data/db/
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
networks:
  default:
    name: dpsrv
    external: true
volumes:
  db:
