services:
  dpsrv-mongo:
    build: .
    container_name: dpsrv-mongo
    image: dpsrv/mongo
    env_file:
      - ${DPSRV_HOME}/rc/secrets/mongo/mongo.env
      - ${DPSRV_HOME}/local.env
    ports:
      - '50017:27017'
    volumes:
      - ${DPSRV_HOME}/rc/secrets/mongo/conf/:/etc/mongo/
      - ${DPSRV_HOME}/rc/secrets/common/cert.pem:/etc/mongo/cert.pem
      - db:/data/db/
      - /etc/localtime:/etc/localtime:ro
    command: '--config /etc/mongo/mongod.conf'
    restart: unless-stopped
networks:
  default:
    name: dpsrv
    external: true
volumes:
  db:
