apiVersion: v1
kind: ConfigMap
metadata:
  namespace: dpsrv
  name: mongodb
data:
  MONGODB_PRIMARY: mongodb-0.mongodb.dpsrv.svc.cluster.local
  # MANUAL: MONGODB_PRIMARY is the only electable member
  # AUTO:   all members are electable, MONGODB_PRIMARY only bootstraps the replica set
  MONGODB_REPLICATION_MODE: MANUAL
