apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: dpsrv
  name: mongodb
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:7.0
          #command: ["mongod", "--config", "/etc/mongo/mongod.conf"]
          command: ["sleep", "infinity"]
          ports:
            - containerPort: 27017
              name: mongodb
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-conf-admin-username
                  key: admin-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-conf-admin-password
                  key: admin-password
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
            - name: mongo-conf-mongod
              mountPath: /etc/mongo/mongod.conf
              subPath: mongod.conf
            - name: mongo-conf-cert
              mountPath: /etc/mongo/cert.pem
              subPath: cert.pem
            - name: mongo-conf-key
              mountPath: /etc/mongo/dpsrv.key
              subPath: dpsrv.key
      volumes:
        - name: mongodb-data
          hostPath:
            path: /mnt/mongodb
            type: DirectoryOrCreate
        - name: mongo-conf-mongod
          secret:
            secretName: mongo-conf-mongod.conf
        - name: mongo-conf-cert
          secret:
            secretName: mongo-conf-cert.pem
        - name: mongo-conf-key
          secret:
            secretName: mongo-conf-dpsrv.key
